server:
    port: 8082


spring:
    cloud:
        function:
            definition: receiveMessage;produceMessage
        stream:
            bindings:
                # following used from  @GetMapping("/message/{id}")
                # User Contoller
                produceMessage-out-0:
                    destination: my-topic

                receivemessage-in-0:
                    destination: my-topic
                    group: my-consumer-group
            kafka:
                binder:
                    configuration:
                        key.serializer: org.apache.kafka.common.serialization.StringSerializer
                    brokers:
                        - localhost:9092




    application:
        name: "users"

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: "*"


    endpoint:
            health:
                   show-details: always
            metrics:
                show-details: always

