server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        gateway:
            access: unrestricted
    info:
        env:
            enabled: true

